from typing import TypedDict, List

class TopicState(TypedDict):
    """Class implementation for a topic of notes.

    Atributes:
      topic_name (str): the name of the topic.
      topic_dir (str): the path for the topic directory.
      index (str): the content of the index.qmd file of the topic.
      files (List[str]): a list with the paths of each .qmd file  of the topic.
      suggestions_path (str): the path for the suggestions file.
      suggestions (str): the suggestions of the LLM for the topic. 
      suggestions_count (int): the number of suggestions generated by the LLM.
    """ 
    topic_name: str
    topic_dir: str
    index: str
    files: List[str]
    suggestions_path: str
    suggestions: str
    suggestions_count: int